### ISSUE TITLE
Uncraftable stone tools

### ISSUE THREAD

**Issue by krjencik** [Craftjakob/More-Bows-CJ#1]
one or some or all if these mods: More bows CJ , Enderite CJ and Gilded Netherite CJ causes stone tools to be uncraftable.

Minecraft 1.19.4 Forge 45.0.49

**Comment by Craftjakob** [comment]
Maybe I know why. Wait, I watch and maybe today you get an update!

**Comment by Craftjakob** [comment]
Yes, I know why you get it wait!
