### ISSUE TITLE
gilded bows not craftable in Minecraft 1.20

### ISSUE THREAD

**Issue by FullMetalMaster** [Craftjakob/More-Bows-CJ#2]
![image](https://github.com/Craftjakob/More-Bows-CJ/assets/52523300/5bc1e8dd-77bf-42b5-a5fb-f0f643dc9e8a)
![image](https://github.com/Craftjakob/More-Bows-CJ/assets/52523300/cfe81bac-5cc2-47fc-aa29-986c071ad7a8)

**Comment by Craftjakob** [comment]
You need to install a new mod, [Gilded Netherite CJ Edition.](https://www.curseforge.com/minecraft/mc-mods/gilded-netherite-cj-edition)
